# Copied from https://github.com/kennytm/extprim/blob/master/.travis.yml :)

language: rust
sudo: false

addons:
    apt:
        packages:
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - binutils-dev
            - gcc-multilib

os:
    - linux

rust:
    - 1.8.0
    - beta
    - nightly

env:
    matrix:
        - ARCH=x86_64
        - ARCH=i686

install:
    - mkdir -p ~/.cargo/bin
    - |
        wget https://github.com/SimonKagstrom/kcov/archive/v31.tar.gz &&
        tar xzf v31.tar.gz &&
        cd kcov-31 &&
        mkdir build &&
        cd build &&
        cmake .. &&
        make &&
        cp src/kcov src/libkcov_sowrapper.so ~/.cargo/bin &&
        cd ../..
    - SYSROOT=$(rustc --print sysroot)
    - export HOST=$ARCH-unknown-linux-gnu
    - |
        if [ ! -d "$SYSROOT/lib/rustlib/$HOST" ]; then
            curl -SfLO "https://static.rust-lang.org/dist/rust-$TRAVIS_RUST_VERSION-$HOST.tar.gz" &&
            tar xf "rust-$TRAVIS_RUST_VERSION-$HOST.tar.gz" "rust-$TRAVIS_RUST_VERSION-$HOST/rust-std-$HOST/lib/rustlib/$HOST" &&
            mv "rust-$TRAVIS_RUST_VERSION-$HOST/rust-std-$HOST/lib/rustlib/$HOST" "$SYSROOT/lib/rustlib"
        fi

before_script:
    - pip install 'travis-cargo<0.2' --user
    - export PATH=$HOME/.local/bin:$HOME/.cargo/bin:$HOME/Library/Python/2.7/bin:$PATH
    - kcov --version

script:
    - cargo test --target "$HOST"

after_success:
    - travis-cargo coveralls --no-sudo --verify -- --bin cargo-kcov
#    - cargo clean
#    - cargo run -- kcov --bin cargo-kcov --coveralls -- --verify

