language: rust
sudo: false

addons:
    apt:
        packages:
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - binutils-dev
            - gcc-multilib

os:
    - linux

rust:
    - 1.8.0
    - 1.9.0
    - beta
    - nightly

env:
    matrix:
        - ARCH=x86_64
        - ARCH=i686

install:
    # 1. Install kcov v31.
    - mkdir -p ~/.cargo/bin
    - |
        wget https://github.com/SimonKagstrom/kcov/archive/v31.tar.gz &&
        tar xzf v31.tar.gz &&
        cd kcov-31 &&
        mkdir build &&
        cd build &&
        cmake .. &&
        make &&
        cp src/kcov src/libkcov_sowrapper.so ~/.cargo/bin &&
        cd ../..
    - export PATH=$HOME/.local/bin:$HOME/.cargo/bin:$HOME/Library/Python/2.7/bin:$PATH
    - kcov --version

    # 2. Install cross-compiling toolchain.
    - SYSROOT=$(rustc --print sysroot)
    - export HOST=$ARCH-unknown-linux-gnu
    - |
        if [ ! -d "$SYSROOT/lib/rustlib/$HOST" ]; then
            curl -SfLO "https://static.rust-lang.org/dist/rust-$TRAVIS_RUST_VERSION-$HOST.tar.gz" &&
            tar xf "rust-$TRAVIS_RUST_VERSION-$HOST.tar.gz" "rust-$TRAVIS_RUST_VERSION-$HOST/rust-std-$HOST/lib/rustlib/$HOST" &&
            mv "rust-$TRAVIS_RUST_VERSION-$HOST/rust-std-$HOST/lib/rustlib/$HOST" "$SYSROOT/lib/rustlib"
        fi

script:
    - RUSTFLAGS="-C link-dead-code" cargo test --target "$HOST"

after_success:
    # Note: we skip the `check-specimen` test in coverage because kcov cannot do recursive-ptrace.
    # Track this file: https://github.com/SimonKagstrom/kcov/blob/master/tests/recursive-ptrace/main.cc
    - cargo run -- kcov --target "$HOST" --no-clean-rebuild --lib --coveralls -- --verify

