[package]
name = "cargo-kcov"
version = "0.4.0"
authors = ["kennytm <kennytm@gmail.com>"]
description = "Cargo subcommand to run kcov to get coverage report on Linux"
repository = "https://github.com/kennytm/cargo-kcov"
keywords = ["cargo", "subcommand", "kcov", "coverage"]
license = "MIT"

[badges]
travis-ci = { repository = "kennytm/cargo-kcov" }

[dependencies]
clap = "2.22.2"
shlex = "0.1.1"
term = "0.4.5"
rustc-serialize = "0.3.23" # use serde instead? we just use it to parse a simple JSON...
regex = "0.2.1"
open = "1.2.0"

[dev-dependencies]
rquery = "0.3.1"
tempdir = "0.3.5"

