name: Build & test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install build dependencies for kcov
      run: apt-get install binutils-dev libssl-dev libcurl4-openssl-dev zlib1g-dev libdw-dev libiberty-dev
    - name: Build
      run: cargo build --verbose
    - name: Install kcov
      run: cargo run -- kcov --print-install-kcov-sh | sh
    - name: Run tests
      run: cargo test --verbose
